export const apiURL = "http://15.235.131.29:8080"
export const DOMAIN = "/api/domains"
export const MOBI = "/api/mobile"
export const VIETEL = "/api/viettel"
export const VINA = "/api/vina"
export const LONGPOLING = "/api/long-polling"
export const SSE = "/sse"