export const apiURL = "http://51.79.208.204"
export const DOMAIN = "/api/domains"
export const MOBI = "/api/mobile"
export const VIETEL = "/api/viettel"
export const VINA = "/api/vina"
export const LONGPOLING = "/api/long-polling"
export const SSE = "/api/sse"